version: "3"
services: 

  dance_demo:
    build: 
        context: ./
    image: [YOUR_REPOSITORY_URI]:latest
 
  jetbot_base:
    image: [YOUR_REPOSITORY_URI]:latest
    command: ros2 launch jetbot_base jetbot.launch.py
    devices:
      - "/dev/i2c-1:/dev/i2c-1"
      - "/dev/video0:/dev/video0"
    volumes:
      - /tmp/argus_socket:/tmp/argus_socket
    environment:
      - DEFAULT_SPEED=0.3
      - QT_X11_NO_MITSHM=1
      - NVIDIA_DRIVER_CAPABILITIES=all
      - CAMERA=false
      - ROS_DOMAIN_ID=0
      - WLAN0_IP="192.168.0.179"
      - ETH0_IP="192.168.0.179"
  
  dance:
    image: [YOUR_REPOSITORY_URI]:latest
    command: ros2 launch jetbot_move dance.launch.py
    environment:
      - DANCE_ROUTINE_PATH:/home/ubuntu/routines/$LOADED_ROUTINE
      - AUTO_START
    volumes: 
      - "/home/ggc_user/routines:/home/ubuntu/routines"
    
  greengrass_bridge:
    image: [YOUR_REPOSITORY_URI]:latest
    command: "ros2 launch greengrass_bridge greengrass_bridge.launch.py ros_topics:=\"['chatter']\" iot_topics:=\"['/jetbot/dance/start', '/jetbot/dance/demo']\""
    environment:
      - AWS_REGION
      - AWS_IOT_THING_NAME
      - SVCUID
      - AWS_GG_NUCLEUS_DOMAIN_SOCKET_FILEPATH_FOR_COMPONENT
      - AWS_CONTAINER_AUTHORIZATION_TOKEN
      - AWS_CONTAINER_CREDENTIALS_FULL_URI
    volumes: 
      - $AWS_GG_NUCLEUS_DOMAIN_SOCKET_FILEPATH_FOR_COMPONENT:$AWS_GG_NUCLEUS_DOMAIN_SOCKET_FILEPATH_FOR_COMPONENT